---
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - ${WEAVIATE_PORT}
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.32.1
    ports:
    - ${WEAVIATE_PORT}:${WEAVIATE_PORT}
    - ${GRPC_PORT}:50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'
      ENABLE_MODULES: 'text2vec-ollama,generative-ollama'
      CLUSTER_HOSTNAME: 'node1'

volumes:
  weaviate_data: